### ISSUE TITLE
nginx host

### ISSUE THREAD

**Issue by strixBE** [projectcaluma/charts#5]
Demoinstall in linting pipeline shows the following error:
```
==> Logs of container caluma-96qcfwy9ky-frontend-79d4596df-p8m5j
------------------------------------------------------------------------------------------------------------------------
2020/03/26 10:43:23 [emerg] 1#1: host not found in upstream "caluma" in /etc/nginx/conf.d/default.conf:19
nginx: [emerg] host not found in upstream "caluma" in /etc/nginx/conf.d/default.conf:19
```

Solution: remove nginx from frontend or solve host problem

Reference: https://github.com/projectcaluma/charts/pull/4/checks?check_run_id=536108537

**Comment by hairmare** [comment]
We might want to override the nginx.conf from a configmap to solve this. The underlying issue stems from the caluma-demo though.

https://github.com/projectcaluma/caluma-demo/blob/a6f41d8ec05ce69a828f2a8347af61e8f03a7389/caluma-demo/nginx.conf#L19

I guess it would make even more sense to fix the broken nginx.config over there.

**Comment by tongpu** [comment]
We should fix it over there. Any fix we would implement here is just going to be a hack.

**Comment by strixBE** [comment]
which would mean to solve the issue that's been open for quite some time: https://github.com/projectcaluma/caluma-demo/issues/15

closing here in favor of the upstream issue.
